'use strict';
const express = require('express');
const router = express.Router();
const mailerlitecontroller = require('./../controller/mailerlite');
router.get('/',  mailerlitecontroller.index);
router.post('/addgroup',  mailerlitecontroller.addgroup);
router.post('/addsubscribertogroup',  mailerlitecontroller.addsubscribertogroup);
router.get('/viewallgroup',  mailerlitecontroller.viewallgroup);
router.get('/viewsubscriber',  mailerlitecontroller.viewsubscriber);
router.get('/calculater',  mailerlitecontroller.getCalculator);
router.post('/addfield',  mailerlitecontroller.addfield);
module.exports = router;
